spring:
  application:
    name: discovery-server
  config:
    import: "optional:configserver:http://localhost:8888" # es donde va buscar las configuraciones del servidor

#Configuraciones de eureka StandAlone, pero que estan
#en config server con su propio yml

#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: localhost #En entorno de producion deber modificarlo al apropiado
#  client:
#    register-with-eureka: false # El servicio no se va registrar en eureka como cliente
#    fetch-registry: false # El cliente no va descargar el registro en eureka.
#    service-url: # La url del servicio
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/